---
# tasks file for oracle-java10 repository and package installation

- name: Add Oracle java apt repository
  become: true
  apt_repository:
    repo: ppa:linuxuprising/java

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install software-properties-common apt package
  become: true
  apt:
    name: software-properties-common

- name: Configure Oracle license options
  become: true
  shell: echo "oracle-java10-installer shared/accepted-oracle-license-v1-1 {{ item }} true"  | debconf-set-selections
  with_items:
    - select
    - seen

- name: Install java 10 apt package
  become: true
  apt:
    name: oracle-java10-installer
    state: present

- name: Set Java 10 as default
  become: true
  when: (force_default_java == "oracle_java10")
  apt:
    name: oracle-java10-set-default
    state: present
